services:
  aion-6g:
    build: .
    container_name: aion-6g-app
    ports:
      - "8000:8000"
    environment:
      - LOCAL_WORKER_URL=http://aion-6g:8000
      - KUBERNETES_WORKER_URL=http://kubernetes-edge:8002
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
